config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  resources :advertisements, only: %i[show index]
  resources :users

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'advertisements#index'

  resources :pictures, only: %i[create destroy]
  resources :categories, only: [:show]

  namespace :admin do
    resources :categories
    resources :advertisements, except: %i[new create edit]
    resources :users
  end

  namespace :users do
    resources :advertisements
    resources :categories, only: [:show]
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  # has_one :profile, dependent: :destroy
  # after_create :create_profile

  has_many :advertisements, dependent: :destroy

  def self.create_new_user(params)
    @user = User.create!(params)
  end

  private

  def create_role
    roles << Role.find_by_name(:user)
  end
end

app/controllers/admin/users_controller.rb
# frozen_string_literal: true

class Admin::UsersController < UsersController
  # before_filter :set_search
  before_action :authenticate_user!
  layout 'admin'

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @user_advertisements = @user.advertisements.result.paginate(page: params[:page], per_page: 10)
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_path
    # set_flash_message :notice, :destroyed
    # sign_out_and_redirect(self.resource)
  end

  def new
    # authorize! :manage, User
    @user = User.new
end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_users_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password,
                                 :password_confirmation, :first_name, :last_name, :username, :birthday)
  end
end

app/controllers/users/advertisements_controller.rb
# frozen_string_literal: true

class Users::AdvertisementsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_advertisement, only: %i[edit update destroy]

  def index
    # @users = User.all
    @user = User.find(params[:id])
    @user_advertisements = @user.advertisements # .paginate(page: params[:page], per_page: 5)
  end

  def show; end

  def to_fresh
    @advertisement.to_fresh!
    redirect_to users_advertisements_path
  end

  def new
    # @advertisement = Advertisement.new
    @advertisement = current_user.advertisements.build
  end

  def create
    @advertisement = current_user.advertisements.create(advertisement_params)
    if @advertisement.save
      redirect_to @advertisement, success: 'Объявление создано'
    else
      flash.now[:danger] = 'Статья не создана'
      render :new
    end
  end

  def edit; end

  def update
    if @advertisement.update_attributes(advertisement_params)
      @advertisement.to_draft
      redirect_to @advertisement, success: 'Объявление отредактировано успешно'
    else
      flash.now[:danger] = '...что-то пошло не так...'
      render :edit
    end
  end

  def destroy
    @advertisement.destroy
    redirect_to advertisements_path, success: 'Объявление уничтожено успешно'
  end

  private

  def set_advertisement
    @advertisement = Advertisement.find(params[:id])
  end

  def advertisement_params
    params.require(:advertisement).permit(:title, :body, :image, :category_id, :state_event, :user_id)
  end
end

app/controllers/users/users_controller.rb
# frozen_string_literal: true

class Users::UsersController < Users::UsersController
  # load_and_authorize_resource
  # before_action :authenticate_user!

  def index
    @user = User.find(params[:id])
    @user_advertisements = @user.advertisements # .paginate(page: params[:page], per_page: 10)
  end

  def show
    @user = User.find(params[:id])
    @user_advertisements = @user.advertisements
  end

  def show_published
    @user = User.find(params[:id])
  end

  def show_archived
    @q = Advertisement.where("state = 'archived' ").ransack(params[:q])
  end

  def show_approved
    @q = Advertisement.where("state = 'approve' ").ransack(params[:q])
  end

  def show_rejected
    @q = Advertisement.where("state = 'rejected' ").ransack(params[:q])
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @user_advertisements = @user.advertisements # .paginate(page: params[:page], per_page: 10)
  end

  def destroy
    resource.destroy
    set_flash_message :notice, :destroyed
    sign_out_and_redirect(resource)
  end
end

app/views/users/_delimeter.html.slim
.page_delimeter
  | Страница 
  = params[:page]

app/views/users/show.html.slim
- # if user_signed_in?
h1
  = "Привет!" + " " + @user.first_name + " " + @user.last_name
.btn-toolbar
  = button_to "Редактировать профиль", edit_user_registration_path, method: :get, class: "btn-group"
  = button_to "Все", current_user, method: :get, class: "btn-group"
  = button_to "В архиве", method: :get,  class: "btn-group"
  = button_to "Опубликованные", class: "btn-group"
  = button_to "Отклоненные", class: "btn-group"
  = button_to "Ждут публикации", class: "btn-group"
  = button_to "Черновик", class: "btn-group"
- @user_advertisements.each do |advertisement|
  article.advertisement
    section.advertisement-head
      h1
        - #= advertisement.title
        = link_to advertisement.title, advertisement_path(advertisement)
      small
        time
          = advertisement.created_at.to_date.strftime( "%e %B %Y %H:%M:%S" )
        - if advertisement.category.present?
          = link_to advertisement.category.name, advertisement.category
        = button_to 'Редактировать', edit_users_advertisement_path(advertisement), method: :get
        = button_to 'Уничтожить', users_advertisement_path(advertisement), method: :delete, data: { confirm: 'Вы уверены?' }
        = button_to 'Отправить в очередь', users_advertisement_path(advertisement), params: { advertisement: { state_event: 'to_fresh'}}, method: :patch
    section.advertisement-body
      = advertisement.body
      = image_tag advertisement.image.url(:large), class: 'img-show' if advertisement.image?
    = advertisement.state
- # end