config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  resources :advertisements, only: %i[show index]
  resources :users

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'advertisements#index'

  resources :pictures, only: %i[create destroy]
  resources :categories, only: [:show]

  namespace :admin do
    resources :categories
    resources :advertisements, except: %i[new create edit]
    resources :users
  end

  namespace :users do
    resources :advertisements
    resources :categories, only: [:show]
  end
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :advertisements
  validates :name, presence: true
  has_ancestry
end

app/controllers/admin/categories_controller.rb
# frozen_string_literal: true

class Admin::CategoriesController < Admin::AdminController
  before_action :set_category, only: %i[edit update destroy]
  # before_filter :set_search

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
    @categories = Category.all.order(:name)
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to admin_categories_path, success: 'Категория успешно создана'
    else
      @categories = Category.all.order(:name)
      flash[:danger] = 'Категория не создана'
      render :new
    end
  end

  def edit
    @categories = Category.where("id != #{@category.id}").order(:name)
  end

  def update
    if @category.update_attributes(category_params)
      redirect_to admin_categories_path, success: 'Категория успешно обновлена'
    else
      @categories = Category.where("id != #{@category.id}").order(:name)
      flash[:danger] = 'Категория не обновлена'
      render :edit
    end
  end

  def destroy
    @category.destroy
    redirect_to admin_categories_path, success: 'Категория успешно удалена'
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :parent_id)
  end
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

class CategoriesController < ApplicationController
  before_action :set_category, only: :show

  def show
    @q = Advertisement.where(state: 'published', category_id: [@category.subtree_ids]).ransack(params[:q])
    @advertisements = @q.result.paginate(page: params[:page], per_page: 10)

    # @advertisements = Advertisement.where(category_id: [@category.subtree_ids]).paginate(page: params[:page], per_page: 5)
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end
end

app/views/admin/categories/_form.html.slim
- if @category.errors.any?
  .alert.alert-danger
    h5
      = t('common.errors')
    ul
      - @category.errors.full_messages.each do |message|
        li
          = message
= form_for [:admin, @category] do |f|
  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :parent_id
    = f.collection_select :parent_id, @categories, :id, :name, { include_blank: true }, class: 'form-control'
  .form-group
    = f.submit t('.submit', action: @category.new_record? ? t('common.create'): t('common.edit')), class: 'btn btn-primary'
    = link_to 'Назад', :back, class: 'btn btn-outline-secondary'

app/views/admin/categories/edit.html.slim
h1
  | Редактирование категории
= render 'form'

app/views/admin/categories/index.html.slim
h1
  | Редактор категорий
.buttons_panel
  = link_to 'Новая категория', new_admin_category_path, class: 'btn btn-outline-primary btn-sm'
section#categories
  table.table
    thead
      tr
        th
          | #
        th
          | Название
        th
          | Категория родитель
        th
    tbody
      - @categories.each_with_index do |category, index|
        tr
          td
            = index + 1
          td
            = category.name
          td
            = category.parent.name if category.parent.present?
          td
            = link_to 'Изменить', edit_admin_category_path(category), class: 'btn btn-outline-primary btn-sm'
            = button_to 'Удалить', admin_category_path(category), method: :delete, data: { confirm: 'Вы уверены?' }, class: 'btn btn-outline-danger btn-sm'

app/views/admin/categories/new.html.slim
h1
  |  Новая категория 
= render 'form'