config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  resources :advertisements, only: %i[show index]
  resources :users

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'advertisements#index'

  resources :pictures, only: %i[create destroy]
  resources :categories, only: [:show]

  namespace :admin do
    resources :categories
    resources :advertisements, except: %i[new create edit]
    resources :users
  end

  namespace :users do
    resources :advertisements
    resources :categories, only: [:show]
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  # has_one :profile, dependent: :destroy
  # after_create :create_profile

  has_many :advertisements, dependent: :destroy

  def self.create_new_user(params)
    @user = User.create!(params)
  end

  private

  def create_role
    roles << Role.find_by_name(:user)
  end
end

app/controllers/admin/users_controller.rb
# frozen_string_literal: true

class Admin::UsersController < UsersController
  # before_filter :set_search
  before_action :authenticate_user!
  layout 'admin'

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @user_advertisements = @user.advertisements.result.paginate(page: params[:page], per_page: 10)
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_path
    # set_flash_message :notice, :destroyed
    # sign_out_and_redirect(self.resource)
  end

  def new
    # authorize! :manage, User
    @user = User.new
end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_users_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password,
                                 :password_confirmation, :first_name, :last_name, :username, :birthday)
  end
end

app/controllers/users/advertisements_controller.rb
# frozen_string_literal: true

class Users::AdvertisementsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_advertisement, only: %i[edit update destroy]

  def index
    # @users = User.all
    @user = User.find(params[:id])
    @user_advertisements = @user.advertisements # .paginate(page: params[:page], per_page: 5)
  end

  def show; end

  def to_fresh
    @advertisement.to_fresh!
    redirect_to users_advertisements_path
  end

  def new
    # @advertisement = Advertisement.new
    @advertisement = current_user.advertisements.build
  end

  def create
    @advertisement = current_user.advertisements.create(advertisement_params)
    if @advertisement.save
      redirect_to @advertisement, success: 'Объявление создано'
    else
      flash.now[:danger] = 'Статья не создана'
      render :new
    end
  end

  def edit; end

  def update
    if @advertisement.update_attributes(advertisement_params)
      @advertisement.to_draft
      redirect_to @advertisement, success: 'Объявление отредактировано успешно'
    else
      flash.now[:danger] = '...что-то пошло не так...'
      render :edit
    end
  end

  def destroy
    @advertisement.destroy
    redirect_to advertisements_path, success: 'Объявление уничтожено успешно'
  end

  private

  def set_advertisement
    @advertisement = Advertisement.find(params[:id])
  end

  def advertisement_params
    params.require(:advertisement).permit(:title, :body, :image, :category_id, :state_event, :user_id)
  end
end

app/controllers/users/users_controller.rb
# frozen_string_literal: true

class Users::UsersController < Users::UsersController
  # load_and_authorize_resource
  # before_action :authenticate_user!

  def index
    @user = User.find(params[:id])
    @user_advertisements = @user.advertisements # .paginate(page: params[:page], per_page: 10)
  end

  def show
    @user = User.find(params[:id])
    @user_advertisements = @user.advertisements
  end

  def show_published
    @user = User.find(params[:id])
  end

  def show_archived
    @q = Advertisement.where("state = 'archived' ").ransack(params[:q])
  end

  def show_approved
    @q = Advertisement.where("state = 'approve' ").ransack(params[:q])
  end

  def show_rejected
    @q = Advertisement.where("state = 'rejected' ").ransack(params[:q])
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @user_advertisements = @user.advertisements # .paginate(page: params[:page], per_page: 10)
  end

  def destroy
    resource.destroy
    set_flash_message :notice, :destroyed
    sign_out_and_redirect(resource)
  end
end

app/views/admin/users/edit.html.slim
h2
  |  "админ" Редактирование пользователя
= form_for(resource, as: resource_name, url: registration_path(resource_name), html: { method: :put }) do |f|
  = render "devise/shared/error_messages", resource: resource
  .field
    = f.label :first_name
    br
    = f.text_field :first_name, autofocus: true
  .field
    = f.label :last_name
    br
    = f.text_field :last_name, autofocus: true
  .field
    = f.label 'Роль'
    br
    = f.text_field :admin, autofocus: true
  .field
    = f.label :username
    br
    = f.text_field :username, autofocus: true
  .field
    = f.label :birthday
    br
    = f.date_field :birthday, autofocus: true
  .field
    = f.label :email
    br
    = f.email_field :email, autofocus: true, autocomplete: "email"
  - if devise_mapping.confirmable? && resource.pending_reconfirmation?
    div
      | Currently waiting confirmation for: 
      = resource.unconfirmed_email
  .field
    = f.label :password
    i
      | (leave blank if you don't want to change it)
    br
    = f.password_field :password, autocomplete: "new-password"
    - if @minimum_password_length
      br
      em
        = @minimum_password_length
        |  characters minimum
  .field
    = f.label :password_confirmation
    br
    = f.password_field :password_confirmation, autocomplete: "new-password"
  .field
    = f.label :current_password
    i
      | (we need your current password to confirm your changes)
    br
    = f.password_field :current_password, autocomplete: "current-password"
  .actions
    = f.submit "Update"
h3
  | Cancel my account
p
  | Unhappy? 
  = button_to "Cancel my account", registration_path(resource_name), data: { confirm: "Are you sure?" }, method: :delete
= link_to "Back", :back

app/views/admin/users/index.html.slim
h1
  | Таблица пользователей
.buttons_panel
  = button_to "Добавить пользователя", new_admin_user_path, method: :get, class: "btn btn-dark"
section#users
  table.table.table-bordered
    thead.thead-dark
      tr
        th[scope="col"]
          | #
        th[scope="col"]
          | action
        th[scope="col"]
          | id
        th[scope="col"]
          | admin?
        th[scope="col"]
          | Дата регистрации
        th[scope="col"]
          | Имя
        th[scope="col"]
          | Фамилия
        th[scope="col"]
          | Username
        th[scope="col"]
          | e-mail
    tbody
      - @users.each do |user|
        tr
          th[scope="row"]
          td
            = button_to "Уничтожить", admin_user_path(user.id),  method: :delete, confirm: 'Are You Sure?'
            = button_to "Редактировать", edit_admin_user_path(user.id), method: :get, confirm: 'Are You Sure?'
          td
            = user.id
          td
            = user.admin
          td
            = user.created_at
          td
            = user.first_name
          td
            = user.last_name
          td
            = user.username
          td
            = user.email

app/views/admin/users/new.html.slim
h1
  |  Админ: добавление нового пользователя 
= form_for [:admin, @user], html: { multipart: true } do |f|
  = render "devise/shared/error_messages", resource: resource
  .field
    = f.label "Имя"
    br
    = f.text_field :first_name, autofocus: true
  .field
    = f.label "Фамилия"
    br
    = f.text_field :last_name, autofocus: true
  .field
    = f.label 'Роль'
    br
    = f.text_field :admin, autofocus: true
  .field
    = f.label :username
    br
    = f.text_field :username, autofocus: true
  .field
    = f.label "Дата рождения"
    br
    = f.date_field :birthday, autofocus: true
  .field
    = f.label :email
    br
    = f.email_field :email, autofocus: true, autocomplete: "email"
  .field
    = f.label "Пароль"
    - if @minimum_password_length
      em
        | (
        = @minimum_password_length
        |  characters minimum)
    br
    = f.password_field :password, autocomplete: "new-password"
  .field
    = f.label :password_confirmation
    br
    = f.password_field :password_confirmation, autocomplete: "new-password"
  .actions
    = f.submit "Сохранить"

app/views/admin/users/show.html.erb
<table class="table">
	<thead>
		<tr>
			<th scope="col">#</th>
			<th scope="col">action</th>
			<th scope="col">id</th>
			<th scope="col">Дата регистрации</th>
			<th scope="col">Имя</th>
			<th scope="col">Фамилия</th>
			<th scope="col">Username</th>
			<th scope="col">e-mail</th>
		</tr>
	</thead>
	<tbody>
		<% @users.each do |user| %>
		<tr>

			<th scope="row"></th>
			<td> 
				<%= button_to "Уничтожить", edit_user_registration_path(user.id) %>
				<button type="button" class="btn btn-dark">Редактировать</button>
			</td>
			<td><%= user.id %></td>
			<td><%= user.created_at %></td>
			<td><%= user.first_name %></td>
			<td><%= user.last_name %></td>
			<td><%= user.username %></td>
			<td><%= user.email %></td>
			<% end %></tr>
		</tbody>
	</table>
	